CREATE TABLE users (
	user_id SERIAL PRIMARY NOT NULL,
	username VARCHAR(50) NOT NULL,
	password VARCHAR(50) NOT NULL,
	status BOOLEAN NOT NULL
);

ALTER TABLE users ADD CONSTRAINT UQ_USERNAME UNIQUE (username);